### ISSUE TITLE
Two tests fail

### ISSUE THREAD

**Issue by jaroslavknotek** [denballakh/ranger-tools#14]
For running unit tests:
```
python -m unittest
```

I receive an output:
```
E...............E
======================================================================
ERROR: test_buffer (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_buffer
Traceback (most recent call last):
  File "/home/jry/.pyenv/versions/3.10.9/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/jry/.pyenv/versions/3.10.9/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/jry/source/ranger-tools/test/test_buffer.py", line 7, in <module>
    from rangers.std._buffer import Buffer as _Buffer, IBuffer as _IBuffer, OBuffer as _OBuffer
ModuleNotFoundError: No module named 'rangers.std._buffer'


======================================================================
ERROR: test_dat (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_dat
Traceback (most recent call last):
  File "/home/jry/.pyenv/versions/3.10.9/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/jry/.pyenv/versions/3.10.9/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/jry/source/ranger-tools/test/test_dat.py", line 89, in <module>
    from rangers.std.buffer import Buffer, FastBuffer
ImportError: cannot import name 'FastBuffer' from 'rangers.std.buffer' (/home/jry/source/ranger-tools/rangers/std/buffer.py)


----------------------------------------------------------------------
Ran 17 tests in 0.002s

FAILED (errors=2)
```

Can you fix that?

**Comment by denballakh** [comment]
Fixed in 7be3a702e85c1d88f5c4593d3cc69797c629b430
